title: Lernblog Bibliotheks- und Archivinformatik
author: Isabel von Ah
email: isabel.vonah@stud.fhgr.ch
description: > # this means to ignore newlines
  Vorlage für ein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2020

# social links
github_username:  isabelvonah # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
